baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Categories'
pageRef = '/categories'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
  [params.author]
    name = 'Ben Bitdiddle'
    email = 'benbitdiddle@faketestemail.arpa'
  [params.copyright]
    type = 'Copyright'
    symbol = 'Â©'
    preposition = 'by'
    name = 'Chu the Pup.' # Your name followed by a period.
    statement = 'All rights reserved.'
