baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Categories'
pageRef = '/categories'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
  [params.author]
    name = 'Ben Bitdiddle'
    email = 'benbitdiddle@faketestemail.arpa'
  [params.copyright]
    type = 'Copyright'
    # type = '(no)Copyright'
    # type = 'CC0 1.0 Public Domain: This work has been dedicated to the public domain under the CC0 1.0 Universal Public Domain Dedication.'
    # type = 'CC BY-SA (Attribution-ShareAlike): Requires credit and sharing under the same license.'
    # type = 'CC BY-NC (Attribution-NonCommercial): Allows use but not for commercial purposes.'
    # type = 'CC BY-ND (Attribution-NoDerivatives): Allows sharing but not modifications'
    # type = 'or whatever you like'
    symbol = 'Â©'
    # symbol = 'ðŸ„¯'
    preposition = 'by'
    name = 'John Doe.' # Your name followed by a period.
    # statement = 'All rights reserved.'
    statement = ''
