name = 'chugo'
license = 'MIT'
licenselink = 'https://github.com/chumutt/chugo/LICENSE'
description = 'a hugo theme by chu the pup'
homepage = 'https://github.com/chumutt/chugo'

[author]
  name = 'chu the pup'

[original]
  author = 'vinliao'
  repo = 'https://github.com/vinliao/hugo-starter.git'
